### ISSUE TITLE
TypeScript module error

### ISSUE THREAD

**Issue by grzechu** [ultrasonicsoft/googlemaps-angular6#10]
Hello, 
In your sample project I have the following error message (app.component.ts)
![error](https://user-images.githubusercontent.com/1776947/42773712-6222940e-892e-11e8-9425-828ee642acdf.png)
How can I fix it? 
IDE: VS Code
Thank you.

**Comment by ultrasonicsoft** [comment]
Try second suggestion.

**Comment by grzechu** [comment]
I tried but i got the same error

**Comment by grzechu** [comment]
I tried but error still appears

**Comment by ultrasonicsoft** [comment]
can you share your project on stackblitz? I cloned branch and ran npm install command. After running application I didn't see any issue at all.

Check your typescript global package version as well.

**Comment by ultrasonicsoft** [comment]
can you share code where I can reproduce it? If you clone this repo, run npm install followed by ng serve command, does it works? It works for me.

**Comment by BrandonHerrin** [comment]
If you are using angular6+ you need to use 
/// <reference types="googlemaps" /> 
instead of 
import { } from '@types/googlemaps';

**Comment by SevierCoding** [comment]
Here is a stackoverflow link to the solution:
https://stackoverflow.com/questions/51084724/types-googlemaps-index-d-ts-is-not-a-module

**Comment by gd2710** [comment]
Hi Balrama & SevierCoding,

    I have also tried as per your blog and above Stackoverflow link but still issue remains same.

Here is my code :

import { Component, OnInit, ViewChild } from '@angular/core';
// import {} from 'googlemaps';
/// <reference path="../../../../GoogleMapDemo/node_modules/@types/googlemaps/index.d.ts" />
/// <reference types="googlemaps" />
import {} from '@types/googlemaps';       //error occurs on this line

//Error is : 
[ts] File 'd:/GDWorkspaces/ARA/GoogleMapDemo/node_modules/@types/googlemaps/index.d.ts' is not a module.

@Component({
  selector: 'app-gmap',
  templateUrl: './gmap.component.html',
  styleUrls: ['./gmap.component.css']
})
export class GmapComponent implements OnInit {
  @ViewChild('gmap') gmapElement: any;
  map: google.maps.Map;
  constructor() { }

  ngOnInit() {
    const mapProp = {
      center: new google.maps.LatLng(18.5793, 73.8143), //And finally google is not defined error occurs here
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    this.map = new google.maps.Map(this.gmapElement.nativeElement, mapProp);
  }

}




Thanks
Gajanan D

**Comment by ultrasonicsoft** [comment]
Updated Angular version 6 with same codebase. Checkout what is difference in your project.

#12
