### ISSUE TITLE
Google is not defined

### ISSUE THREAD

**Issue by WiliamGonzalezCobo** [ultrasonicsoft/googlemaps-angular6#19]
ERROR ReferenceError: google is not defined
    at MapComponent.push../src/app/components/map/map.component.ts.MapComponent.ngOnInit (map.component.ts:15)
![errorintermitente](https://user-images.githubusercontent.com/8941003/45230603-f62c5200-b28e-11e8-841e-d24f07b9f1ce.png)
![cargomapa](https://user-images.githubusercontent.com/8941003/45230649-1c51f200-b28f-11e8-846f-27af9c326d3b.png)

**Comment by venkatesh1github** [comment]
I am also getting same error

**Comment by michael-letcher** [comment]
Makes sure to have an API key.
The guide is not good in that it ignores this a makes it seem that you don't need one.
https://developers.google.com/maps/documentation/javascript/tutorial#api-key-billing-errors

**Comment by ultrasonicsoft** [comment]
@michael-letcher Thanks!
